[package]
name = "ant_sim_rs"
version = "0.1.0"
authors = ["plaptov"]
edition = "2018"

[dependencies]
gfx = "0.18"
ggez = "0.4"
rand = "0.6.5"
ignore-result = "0.2.0"
log = "0.4"
color-backtrace = "0.1"